// Starter templates. Installing one creates a DRAFT the user then connects,
// configures, tests and activates. `needs` lists required connections.
const T = (id, category, name, description, difficulty, needs, automation) => ({ id, category, name, description, difficulty, needs, automation });
const sched = (times, days) => ({ integration: 'autometa', key: 'schedule', schedule: { times, ...(days ? { days } : {}) } });
const notify = (id, title, body) => ({ id, type: 'action', integration: 'autometa', action: 'notify', config: { title, body } });
const tgSend = (id, text) => ({ id, type: 'action', integration: 'telegram', action: 'send_message', config: { chatId: '', text } });
const waTpl = (id, template, params = '') => ({ id, type: 'action', integration: 'whatsapp', action: 'send_template', config: { to: '', template, language: 'en_US', params } });
const hook = { integration: 'webhook', key: 'received', config: { webhookId: '' } };

export const CLOUD_TEMPLATES = [
  T('morning_reminder', 'Personal', 'Morning reminder', 'Every morning at 7:00, a reminder from your Telegram bot.', 'Easy', ['telegram'], { name: 'Morning reminder', trigger: sched(['07:00']), steps: [tgSend('s1', 'Good morning! Today is {{weekday}}. Here\'s your plan for the day.')] }),
  T('evening_reminder', 'Personal', 'Evening wind-down', 'A calm nudge every evening at 21:30.', 'Easy', ['telegram'], { name: 'Evening reminder', trigger: sched(['21:30']), steps: [tgSend('s1', 'Time to wind down. Plan tomorrow and put the phone away. 🌙')] }),
  T('daily_checklist', 'Personal', 'Weekday checklist', 'Weekdays at 08:00, your checklist in Autometa notifications.', 'Easy', [], { name: 'Weekday checklist', trigger: sched(['08:00'], [1, 2, 3, 4, 5]), steps: [notify('s1', 'Today\'s checklist', '☐ Inbox zero\n☐ Top 3 tasks\n☐ Exercise')] }),
  T('study_reminder', 'Personal', 'Study reminder', 'Mon/Wed/Fri at 18:00, time to study.', 'Easy', ['telegram'], { name: 'Study reminder', trigger: sched(['18:00'], [1, 3, 5]), steps: [tgSend('s1', '📚 Study session starts now. 45 minutes, phone away.')] }),
  T('medication', 'Personal', 'Medication reminder', 'Reminds you at the times you set. It doesn\'t replace medical advice or alarms for critical medication.', 'Easy', ['telegram'], { name: 'Medication reminder', trigger: sched(['08:00', '20:00']), steps: [tgSend('s1', '💊 Medication reminder ({{time}}).')] }),
  T('wa_reminder', 'Communication', 'WhatsApp appointment reminder', 'Sends an approved WhatsApp template from your business number on a schedule.', 'Medium', ['whatsapp'], { name: 'WhatsApp reminder', trigger: sched(['09:00'], [1, 2, 3, 4, 5]), steps: [waTpl('s1', 'appointment_reminder', '{{date}}')] }),
  T('scheduled_telegram', 'Communication', 'Weekly Telegram announcement', 'Every Monday at 09:00, post to your group or channel.', 'Easy', ['telegram'], { name: 'Monday announcement', trigger: sched(['09:00'], [1]), steps: [tgSend('s1', '📣 New week! Here\'s what\'s happening…')] }),
  T('webhook_notify', 'Developer', 'Webhook → notification', 'When your webhook receives a high-priority event, notify you.', 'Easy', [], { name: 'High-priority webhook alert', trigger: hook, steps: [{ id: 'c1', type: 'condition', mode: 'all', rules: [{ field: 'payload.priority', op: 'eq', value: 'high' }] }, notify('s1', 'High priority: {{payload.event}}', '{{payload.name}} just came in.')] }),
  T('webhook_telegram', 'Developer', 'Webhook → Telegram', 'Forward any webhook event to Telegram.', 'Easy', ['telegram'], { name: 'Webhook to Telegram', trigger: hook, steps: [tgSend('s1', '🔔 {{payload.event}}: {{payload.name}}')] }),
  T('deploy_notify', 'Developer', 'Deployment notification', 'Your CI posts to a webhook; your team hears about it on Telegram.', 'Medium', ['telegram'], { name: 'Deploy notification', trigger: hook, steps: [{ id: 'c1', type: 'condition', mode: 'all', rules: [{ field: 'payload.status', op: 'exists' }] }, tgSend('s1', '🚀 Deploy {{payload.status}}: {{payload.service}} {{payload.version}}')] }),
  T('error_alert', 'Developer', 'Error alert with follow-up', 'Error webhook → instant Telegram alert → reminder after 15 minutes.', 'Medium', ['telegram'], { name: 'Error alert', trigger: hook, steps: [{ id: 'c1', type: 'condition', mode: 'all', rules: [{ field: 'payload.level', op: 'eq', value: 'error' }] }, tgSend('s1', '🔥 {{payload.message}}'), { id: 'd1', type: 'delay', minutes: 15 }, tgSend('s2', '⏰ Still investigating: {{payload.message}}?')] }),
  T('lead_notify', 'Business', 'New lead notification', 'Your website form posts to a webhook; you get the lead on Telegram.', 'Easy', ['telegram'], { name: 'New lead', trigger: hook, steps: [tgSend('s1', '🧲 New lead: {{payload.name}} ({{payload.email}}, {{payload.phone}})\n{{payload.message}}')] }),
  T('daily_summary', 'Business', 'Daily business check-in', 'Weekdays at 18:00, a prompt to review sales and follow-ups.', 'Easy', [], { name: 'Daily check-in', trigger: sched(['18:00'], [1, 2, 3, 4, 5]), steps: [notify('s1', 'Daily check-in', 'Review today\'s orders, reply to open chats, schedule tomorrow\'s follow-ups.')] }),
  T('multi_channel', 'Communication', 'Multi-channel announcement', 'Telegram now, then a WhatsApp template 5 minutes later.', 'Advanced', ['telegram', 'whatsapp'], { name: 'Announcement', trigger: { integration: 'autometa', key: 'manual' }, steps: [tgSend('s1', '📣 Announcement'), { id: 'd1', type: 'delay', minutes: 5 }, waTpl('s2', 'announcement')] }),
];

export const STARTERS = ['morning_reminder', 'webhook_notify', 'scheduled_telegram', 'daily_checklist', 'lead_notify'];
